
          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800 border-bottom">Agregar Productos</h1>
        
        <form action="" method="post" class="form">
            <input type="hidden" name="add" value="1">

            <div class="form-group"><label for="nombre">Name</label><input type="text" name="nombre" id="nombre" class="form-control" placeholder="Name"></div>
            <div class="form-group"><label for="description">Description</label><input type="text" name="descripcion" id="descripcion" class="form-control" placeholder="Description"></div>
            <div class="form-group"><label for="precio">Price</label><input type="text" name="precio" id="precio" class="form-control" placeholder="Price"></div>
            <input type="submit" value="Agregar" class="btn btn-primary">
            
        </form>