-- MySQL Script generated by MySQL Workbench
-- Wed Oct 28 20:21:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tienda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tienda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tienda` DEFAULT CHARACTER SET utf8 ;
USE `tienda` ;

-- -----------------------------------------------------
-- Table `tienda`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`Marca` (
  `id_marca` INT  AUTO_INCREMENT NOT NULL,
  `Nom_marca` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_marca`));


-- -----------------------------------------------------
-- Table `tienda`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`Cliente` (
  `id_Cliente` INT NOT NULL AUTO_INCREMENT ,
  `Nom_cliente` VARCHAR(50) NOT NULL,
   `apellidos` VARCHAR(50) NOT NULL,
    `telefono` varchar(15)NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
PRIMARY KEY (`id_Cliente`));


-- -----------------------------------------------------
-- Table `tienda`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`Proveedor` (
  `id_Proveedor` INT NOT NULL AUTO_INCREMENT,
  `Nom_Proveedor` VARCHAR(45) NOT NULL,
  `telefono` varchar(15)NOT NULL,
  PRIMARY KEY (`id_Proveedor`));


-- -----------------------------------------------------
-- Table `tienda`.`Talla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`Talla` (
  `id_Talla` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`id_Talla`));


-- -----------------------------------------------------
-- Table `tienda`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`id_categoria`));


-- -----------------------------------------------------
-- Table `tienda`.`Prenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`Prenda` (
  `id_Prendas` INT NOT NULL AUTO_INCREMENT,
  `precio` float NOT NULL,
  `cantidad` INT NOT NULL,
  `descripcion` varchar(200) Not Null,
  `Marca_id_marca` INT NOT NULL,
  `Talla_id_Talla`  INT NOT NULL,
  `categoria_id_categoria`  INT NOT NULL,
  `Proveedor_id_Proveedor` INT NOT NULL,

  PRIMARY KEY (`id_Prendas`),

   INDEX `fk_Prenda_Marca1_idx` (`Marca_id_marca` ASC),
   INDEX `fk_Prenda_Talla1_idx` (`Talla_id_Talla` ASC),
   INDEX `fk_Prenda_categoria1_idx` (`categoria_id_categoria` ASC),
   INDEX `fk_Prenda_Proveedor1_idx` (`Proveedor_id_Proveedor` ASC),
CONSTRAINT `fk_Prenda_Marca1`
    FOREIGN KEY (`Marca_id_marca`)
    REFERENCES `tienda`.`Marca` (`id_marca`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

 
CONSTRAINT `fk_Prenda_Talla1`
    FOREIGN KEY (`Talla_id_Talla`)
    REFERENCES `tienda`.`Talla` (`id_Talla`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,   
 
 CONSTRAINT `fk_Prenda_categoria1`
    FOREIGN KEY (`categoria_id_categoria`)
    REFERENCES `tienda`.`categoria` (`id_categoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,   
 
 CONSTRAINT `fk_Prenda_Proveedor1`
    FOREIGN KEY (`Proveedor_id_Proveedor`)
    REFERENCES `tienda`.`Proveedor` (`id_Proveedor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE );


-- -----------------------------------------------------
-- Table `tienda`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`Ventas` (
  `id_Ventas` INT NOT NULL,
  `Fecha` DATE NULL,
  `total` float,
  
  `Cliente_id_Cliente` INT NOT NULL,
  `Prenda_id_Prendas` INT NOT NULL,
  PRIMARY KEY (`id_Ventas`),
  INDEX `fk_Ventas_Cliente1_idx` (`Cliente_id_Cliente` ASC),
  INDEX `fk_Ventas_Prenda1_idx` (`Prenda_id_Prendas` ASC),
  
  CONSTRAINT `fk_Ventas_Cliente1`
    FOREIGN KEY (`Cliente_id_Cliente`)
    REFERENCES `tienda`.`Cliente` (`id_Cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE ,  

     CONSTRAINT `fk_Ventas_Prenda1`
    FOREIGN KEY (`Prenda_id_Prendas`)
    REFERENCES `tienda`.`prenda` (`id_prendas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE );


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
