
          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800 border-bottom">Agregar Proveedor</h1>
        
        <form action="" method="post" class="form">
            <input type="hidden" name="add" value="1">

            <div class="form-group"><label for="nombre">Nombre</label><input type="text" name="nombre" id="nombre" class="form-control" placeholder="Name"></div>
            <div class="form-group"><label for="telefono">telefono</label><input type="text" name="telefono" id="telefono" class="form-control" placeholder="telefono"></div>
            <input type="submit" value="Agregar" class="btn btn-primary">
            
        </form>