
      <?= $this->cate ?>
 <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="card-header">
              </div>
          <div class="col-md-6">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Formulario de registro</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form>
                <div class="card-body">
                  <div class="form-group">
                    <label for="exampleInputEmail1">ID</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Ingrese el id">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1">Nombre Categoría</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Igrese la categoria">
                  </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>