<br><br>
 <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-6">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Formulario de registro</h3>
              </div>
              <form action="" method="post">
                <input type="hidden" name="agregar" value="1">
                <div class="card-body">
                  <div class="row"> 
                  <div class="col-5">
                    <label for="exampleInputPassword1">ID</label>
                    <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Campo desactivado" disabled="">
                  </div>
                  <div class="col-5">
                    <label for="exampleInputPassword1">Nombre categoria</label>
                    <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Ingrese el nombre" required>
                  </div>
                </div>
                </div>
                <div class="card-body">
                  <button type="submit" class="btn btn-primary">
                    <span>
                      <i class="fas fa-arrow-right"></i> Enviar</button>
                    </span>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>