 <div class="modal fade" id="modalEditarcat">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title font-weight-normal">Actualizar Categorias</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form id="formEditcta" method="post" class="form" >
                <input type="hidden" name="editar" value="1">
                <div class="card-body">
                  <input type="hidden" class="form-control" id="id" name="id">
                  <div class="row form-group">
                    <div class="col-sm-2">
                      <label class="control-label" style="position:relative; top:7px;">Nombre:</label>
                    </div>
                    <div class="col-sm-10">
                     <input type="text" class="form-control" id="nombre" name="nombre">
                    </div>
                  </div>
                </div>
            </div>
            <div class="modal-footer justify-content-between">
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
          </form>
          </div>
          <!-- /.modal-content -->
        </div>
      </div>
        <!-- /.modal-dialog -->
      <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Categorias</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Categorias</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
      <div class="content">
      <div class="container-fluid">
       <a href="<?= BASE_URL ?>categorias/agregarc" class="btn btn-secondary btn-icon-split">
            <span class="icon text-white-50">
                <i class="fas fa-plus"></i>
            </span>
            <span class="text">Agregar Nuevo</span>
        </a>
        <div class="row mr-7">
          <div class="col-lg-9"><br>
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Lista de categorías registradas</h3>
              </div>
              <div class="card-body">
                <table  id="e" class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th class="text-center">#</th>
                      <th class="text-center">Nombre</th>
                      <th class="text-center">Acciones</th>
                    </tr>
                  </thead>
                  <tbody>
                      <?=$this->tabla ?>
                  </tbody>
                  <tfoot>
                    <tr>
                      <th class="text-center">#</th>
                      <th class="text-center">Nombre</th>
                      <th class="text-center">Acciones</th>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

