

<div class="content">
      <div class="container-fluid">
               <?= $this->cat ?>
        <div class="row">
          <div class="col-lg-6">
            <div class="card-header">
              </div>
              <div class="card-body">
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th style="width:4px;text-align: center">#</th>
                      <th style="width: 4px;text-align: center">Name</th>
                      <th style="width: 4px;text-align:">Accion</th> 
                    </tr>
                  </thead>
                  <tbody>
                      <?=$this->tabla ?>
                  </tbody>
                </table>
              </div>
          </div>
        </div>
      </div>
    </div>



