<div class="hold-transition login-page" style="margin-left:550px;margin-right:550px;margin-top:150px">  
<section class="content-header">
<div class="login-box">
<?php if (isset($this->mensaje)) echo $this->mensaje;?>
  <div class="card card-outline card-primary">
    <div class="card-header text-center">
    
      <p class="h1 text-primary"><b>FINCA lA BENDICION</p>
    </div>
    <div class="card-body">
      <p class="login-box-msg text-info">Iniciar sesion</p>
      <form action="#" method="post">
         <input type="hidden" name="ingresar" value="1">
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="Usuario" name="usuario" id="usuario" autofocus="">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Password" name="clave" id="clve">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Acceder</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
</section>
</div>