
          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800 border-bottom">Agregar Cliente</h1>
        
        <form action="" method="post" class="form">
            <input type="hidden" name="add" value="1">

            <div class="form-group"><label for="nombre">Nombre</label><input type="text" name="nombre" id="nombre" class="form-control" placeholder="Name"></div>
            <div class="form-group"><label for="apellidos">Apellidos</label><input type="text" name="apellido" id="apellidos" class="form-control" placeholder="apellidos"></div>
            <div class="form-group"><label for="telefono">telefono</label><input type="text" name="telefono" id="telefono" class="form-control" placeholder="telefono"></div>
            <div class="form-group"><label for="direccion">Direccion</label><input type="text" name="direccion" id="direccion" class="form-control" placeholder="direccion"></div>
            <input type="submit" value="Agregar" class="btn btn-primary">
            
        </form>